#Importing Libraries

In [14]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#Loading Dataset

In [15]:
df=pd.read_csv(r'C:\Users\Devil-PC\Desktop\Ultimate_Games_Dataset.csv')

#Data Exploration

In [16]:
df.shape

(15001, 43)

In [17]:
df.head()

,serial_no,game_id,title,release_date,release_year,all_genres,theme,art_style,view_dimension,game_mode,...,cover_image_url,official_website,url_slug,description_clean,popularity_score,engagement_score,decade,is_multi_platform,rating_tier,metacritic_tier
0,1,3498,Grand Theft Auto V,17-09-2013,2013,Action,Crime,Realistic,3D,Single & Multiplayer,...,https://media.rawg.io/media/games/20a/20aa03a1...,http://www.rockstargames.com/V/,grand-theft-auto-v,"Rockstar Games went bigger, since their previo...",96.28,21.75,2010s,1.0,excellent,universal_acclaim
1,2,3328,The Witcher 3: Wild Hunt,18-05-2015,2015,Action|RPG,Fantasy,Realistic,3D,Singleplayer,...,https://media.rawg.io/media/games/618/618c2031...,https://thewitcher.com/en/witcher3,the-witcher-3-wild-hunt,"The third game in a series, it holds nothing b...",95.81,17.19,2010s,1.0,masterpiece,universal_acclaim
2,3,4200,Portal 2,18-04-2011,2011,Shooter|Puzzle,Sci-Fi,Realistic,3D,Single & Multiplayer,...,https://media.rawg.io/media/games/2ba/2bac0e87...,http://www.thinkwithportals.com/,portal-2,Portal 2 is a first-person puzzle game develop...,91.26,15.24,2010s,1.0,masterpiece,universal_acclaim
3,4,4291,Counter-Strike: Global Offensive,21-08-2012,2012,Shooter,Horror,Realistic,3D,Multiplayer,...,https://media.rawg.io/media/games/736/73619bd3...,http://blog.counter-strike.net/,counter-strike-global-offensive,Counter-Strike is a multiplayer phenomenon in ...,73.56,8.79,2010s,1.0,good,generally_favorable
4,5,5286,Tomb Raider (2013),05-03-2013,2013,Action,Adventure,Realistic,3D,Single & Multiplayer,...,https://media.rawg.io/media/games/021/021c4e21...,http://www.tombraider.com,tomb-raider,A cinematic revival of the series in its actio...,76.54,13.77,2010s,1.0,excellent,generally_favorable

In [18]:
df.tail()

,serial_no,game_id,title,release_date,release_year,all_genres,theme,art_style,view_dimension,game_mode,...,cover_image_url,official_website,url_slug,description_clean,popularity_score,engagement_score,decade,is_multi_platform,rating_tier,metacritic_tier
14996,14996,11550,MANOS,30-07-2015,2015,Action|Adventure|Indie,Not Specified,Not Specified,Not Specified,Not Specified,...,https://media.rawg.io/media/screenshots/0e6/0e...,Not Specified,manos,"""This game will be bigger than Skyrim!” - Bill...",1.62,0.0,2010s,0.0,unrated,no_score
14997,14997,327253,Undying,19-10-2021,2021,Adventure|Indie,Not Specified,Not Specified,Not Specified,Not Specified,...,https://media.rawg.io/media/screenshots/b6f/b6...,Not Specified,undying-2,"The top down, 3D indie adventure has you survi...",1.61,0.0,2020s,1.0,unrated,no_score
14998,14998,23143,Sea Dogs: City of Abandoned Ships,11-05-2009,2009,Action|RPG,Not Specified,Not Specified,Not Specified,Not Specified,...,https://media.rawg.io/media/screenshots/485/48...,Not Specified,sea-dogs-city-of-abandoned-ships,Fortune and glory awaits you! In Sea Dogs - Ci...,1.62,0.0,2000s,0.0,excellent,mixed
14999,14999,485167,Combat Arms: the Classic,14-07-2020,2020,Action|Adventure,Not Specified,Not Specified,Not Specified,Not Specified,...,https://media.rawg.io/media/screenshots/3ce/3c...,Not Specified,combat-arms-the-classic,- Combat Arms is an MMOFPS that focuses on mul...,1.61,0.0,2020s,0.0,below_average,no_score
15000,15000,21093,Cubot,08-01-2015,2015,Indie,Not Specified,Not Specified,Not Specified,Not Specified,...,https://media.rawg.io/media/screenshots/b00/b0...,Not Specified,cubot,"At first sight, Cubot is a puzzle-game with a ...",1.62,0.0,2010s,1.0,below_average,no_score

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15001 entries, 0 to 15000
Data columns (total 43 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   serial_no           15001 non-null  str
 1   game_id             15001 non-null  str
 2   title               15001 non-null  str
 3   release_date        15001 non-null  str
 4   release_year        15001 non-null  str
 5   all_genres          15001 non-null  str
 6   theme               15001 non-null  str
 7   art_style           15001 non-null  str
 8   view_dimension      15001 non-null  str
 9   game_mode           15001 non-null  str
 10  is_multiplayer      15001 non-null  str
 11  controls            15000 non-null  str
 12  developers          15000 non-null  str
 13  publishers          15000 non-null  str
 14  all_platforms       15000 non-null  str
 15  platform_count      15000 non-null  float64
 16  esrb_rating         15000 non-null  str
 17  user_rating         14613 non-null  float64
 18  metacritic          14114 non-null  float64
 19  ratings_count       15000 non-null  float64
 20  reviews_count       15000 non-null  float64
 21  library_count       15000 non-null  float64
 22  avg_playtime_hours  15000 non-null  float64
 23  achievements_count  15000 non-null  float64
 24  game_series_count   15000 non-null  float64
 25  status_owned        15000 non-null  float64
 26  status_beaten       15000 non-null  float64
 27  status_playing      15000 non-null  float64
 28  status_dropped      15000 non-null  float64
 29  status_toplay       15000 non-null  float64
 30  status_yet          15000 non-null  float64
 31  all_tags            15000 non-null  str
 32  available_stores    15000 non-null  str
 33  cover_image_url     15000 non-null  str
 34  official_website    15000 non-null  str
 35  url_slug            15000 non-null  str
 36  description_clean   15000 non-null  str
 37  popularity_score    14999 non-null  float64
 38  engagement_score    14999 non-null  float64
 39  decade              14999 non-null  str
 40  is_multi_platform   14999 non-null  float64
 41  rating_tier         14999 non-null  str
 42  metacritic_tier     14999 non-null  str
dtypes: float64(18), str(25)
memory usage: 4.9 MB

#Converting Datatype of release_date from str to datetime

In [20]:
df['release_date'].head(5)

0    17-09-2013
1    18-05-2015
2    18-04-2011
3    21-08-2012
4    05-03-2013
Name: release_date, dtype: str

In [21]:
df['release_date'] = pd.to_datetime(df['release_date'],format='%d-%m-%Y',errors='coerce')

In [22]:
df['release_date'].dtype

dtype('<M8[us]')

#Converting Datatype of release_year from str to float

In [23]:
df['release_year'] = pd.to_numeric(df['release_year'],errors='coerce')

In [24]:
df['release_year'].dtype

dtype('float64')

In [25]:
df.describe()

,release_date,release_year,platform_count,user_rating,metacritic,ratings_count,reviews_count,library_count,avg_playtime_hours,achievements_count,game_series_count,status_owned,status_beaten,status_playing,status_dropped,status_toplay,status_yet,popularity_score,engagement_score,is_multi_platform
count,15000,15000.000000,15000.000000,14613.000000,14114.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,14999.000000,14999.000000,14999.000000
mean,2016-02-27 11:27:10.080000,2015.643267,2.604800,3.274654,70.719265,105.165733,104.721933,745.553400,3.716867,52.601000,1.897133,569.275933,73.721333,8.292533,36.340133,24.528000,36.691067,24.933174,3.813580,0.600307
min,1979-01-01 00:00:00,1979.000000,1.000000,1.000000,23.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.610000,0.000000,0.000000
25%,2014-01-23 18:00:00,2014.000000,1.000000,2.810000,66.000000,2.000000,1.000000,11.000000,1.000000,0.000000,0.000000,9.000000,1.000000,0.000000,1.000000,1.000000,1.000000,20.230000,0.450000,0.000000
50%,2016-11-24 00:00:00,2016.000000,2.000000,3.430000,70.000000,17.000000,15.000000,281.000000,3.000000,10.000000,0.000000,224.500000,5.000000,2.000000,5.000000,4.000000,9.000000,26.500000,1.820000,1.000000
75%,2020-10-14 06:00:00,2020.000000,3.000000,3.800000,75.100000,68.000000,68.000000,743.000000,4.000000,49.000000,0.000000,604.000000,30.000000,5.000000,26.000000,15.000000,35.000000,30.800000,4.250000,1.000000
max,2026-05-26 00:00:00,2026.000000,22.000000,5.000000,99.000000,7153.000000,7268.000000,22126.000000,367.000000,7166.000000,77.000000,14089.000000,6283.000000,949.000000,2101.000000,2440.000000,1181.000000,96.280000,41.930000,1.000000
std,NaN,6.514203,1.869131,0.708470,8.136159,319.697866,320.632844,1506.652519,8.875561,213.815238,5.958645,1079.416333,276.541649,32.800122,103.728662,77.747554,79.647606,10.233381,5.679286,0.489852

In [26]:
df.columns

Index(['serial_no', 'game_id', 'title', 'release_date', 'release_year',
       'all_genres', 'theme', 'art_style', 'view_dimension', 'game_mode',
       'is_multiplayer', 'controls', 'developers', 'publishers',
       'all_platforms', 'platform_count', 'esrb_rating', 'user_rating',
       'metacritic', 'ratings_count', 'reviews_count', 'library_count',
       'avg_playtime_hours', 'achievements_count', 'game_series_count',
       'status_owned', 'status_beaten', 'status_playing', 'status_dropped',
       'status_toplay', 'status_yet', 'all_tags', 'available_stores',
       'cover_image_url', 'official_website', 'url_slug', 'description_clean',
       'popularity_score', 'engagement_score', 'decade', 'is_multi_platform',
       'rating_tier', 'metacritic_tier'],
      dtype='str')

#Checking Duplicate and Null Values

In [27]:
df.duplicated().sum()

np.int64(0)

In [28]:
df.isnull().sum()

serial_no               0
game_id                 0
title                   0
release_date            1
release_year            1
all_genres              0
theme                   0
art_style               0
view_dimension          0
game_mode               0
is_multiplayer          0
controls                1
developers              1
publishers              1
all_platforms           1
platform_count          1
esrb_rating             1
user_rating           388
metacritic            887
ratings_count           1
reviews_count           1
library_count           1
avg_playtime_hours      1
achievements_count      1
game_series_count       1
status_owned            1
status_beaten           1
status_playing          1
status_dropped          1
status_toplay           1
status_yet              1
all_tags                1
available_stores        1
cover_image_url         1
official_website        1
url_slug                1
description_clean       1
popularity_score        2
engagement_score        2
decade                  2
is_multi_platform       2
rating_tier             2
metacritic_tier         2
dtype: int64

#Data Cleaning and Handling Null Values

In [29]:
small_missing_cols = []

for col in df.columns:
    if df[col].isnull().sum() <= 2:
        small_missing_cols.append(col)

df = df.dropna(subset=small_missing_cols)

In [30]:
df.isnull().sum()

serial_no               0
game_id                 0
title                   0
release_date            0
release_year            0
all_genres              0
theme                   0
art_style               0
view_dimension          0
game_mode               0
is_multiplayer          0
controls                0
developers              0
publishers              0
all_platforms           0
platform_count          0
esrb_rating             0
user_rating           387
metacritic            886
ratings_count           0
reviews_count           0
library_count           0
avg_playtime_hours      0
achievements_count      0
game_series_count       0
status_owned            0
status_beaten           0
status_playing          0
status_dropped          0
status_toplay           0
status_yet              0
all_tags                0
available_stores        0
cover_image_url         0
official_website        0
url_slug                0
description_clean       0
popularity_score        0
engagement_score        0
decade                  0
is_multi_platform       0
rating_tier             0
metacritic_tier         0
dtype: int64

#Calculating the Percentage of games that may not have enough user ratings and haven't received a Metacritic score

In [31]:
missing_pct = (df[['user_rating','metacritic']].isnull().sum() / len(df) * 100)

missing_pct

user_rating    2.580172
metacritic     5.907060
dtype: float64

#For Sake of EDA purposes Missing values in user_rating and metacritic is being imputed

In [32]:
df[['user_rating', 'metacritic']].describe()

        user_rating    metacritic
count  14612.000000  14113.000000
mean       3.274589     70.718380
std        0.708451      8.135769
min        1.000000     23.000000
25%        2.810000     66.000000
50%        3.430000     70.000000
75%        3.800000     75.100000
max        5.000000     99.000000

In [33]:
df['user_rating'] = df['user_rating'].fillna(df['user_rating'].median())

df['metacritic'] = df['metacritic'].fillna(df['metacritic'].median())

#Note: choosing median over mean because of slight skewness

In [34]:
df.isnull().sum()

serial_no             0
game_id               0
title                 0
release_date          0
release_year          0
all_genres            0
theme                 0
art_style             0
view_dimension        0
game_mode             0
is_multiplayer        0
controls              0
developers            0
publishers            0
all_platforms         0
platform_count        0
esrb_rating           0
user_rating           0
metacritic            0
ratings_count         0
reviews_count         0
library_count         0
avg_playtime_hours    0
achievements_count    0
game_series_count     0
status_owned          0
status_beaten         0
status_playing        0
status_dropped        0
status_toplay         0
status_yet            0
all_tags              0
available_stores      0
cover_image_url       0
official_website      0
url_slug              0
description_clean     0
popularity_score      0
engagement_score      0
decade                0
is_multi_platform     0
rating_tier           0
metacritic_tier       0
dtype: int64

#Checking Duplicate values in Dataset

In [35]:
df.duplicated().sum()

np.int64(0)

In [36]:
num_cols = df.select_dtypes(include=['int64','float64']).columns

df[num_cols].describe().T

,count,mean,std,min,25%,50%,75%,max
release_year,14999.0,2015.643776,6.514121,1979.00,2014.00,2016.00,2020.00,2026.00
platform_count,14999.0,2.604707,1.869158,1.00,1.00,2.00,3.00,22.00
user_rating,14999.0,3.278599,0.699685,1.00,2.83,3.43,3.79,5.00
metacritic,14999.0,70.675945,7.893620,23.00,66.20,70.00,75.00,99.00
ratings_count,14999.0,105.161544,319.708112,0.00,2.00,17.00,68.00,7153.00
reviews_count,14999.0,104.717648,320.643103,0.00,1.00,15.00,68.00,7268.00
library_count,14999.0,745.548037,1506.702603,0.00,11.00,281.00,743.00,22126.00
avg_playtime_hours,14999.0,3.716781,8.875851,0.00,1.00,3.00,4.00,367.00
achievements_count,14999.0,52.598173,213.822086,0.00,0.00,10.00,49.00,7166.00
game_series_count,14999.0,1.897260,5.958824,0.00,0.00,0.00,0.00,77.00
status_owned,14999.0,569.272552,1079.452239,0.00,9.00,224.00,604.00,14089.00
status_beaten,14999.0,73.716781,276.550306,0.00,1.00,5.00,30.00,6283.00
status_playing,14999.0,8.292820,32.801197,0.00,0.00,2.00,5.00,949.00
status_dropped,14999.0,36.339356,103.732076,0.00,1.00,5.00,26.00,2101.00
status_toplay,14999.0,24.529169,77.750014,0.00,1.00,4.00,15.00,2440.00
status_yet,14999.0,36.693180,79.649841,0.00,1.00,9.00,35.00,1181.00
popularity_score,14999.0,24.933174,10.233381,1.61,20.23,26.50,30.80,96.28
engagement_score,14999.0,3.813580,5.679286,0.00,0.45,1.82,4.25,41.93
is_multi_platform,14999.0,0.600307,0.489852,0.00,0.00,1.00,1.00,1.00

#Removing Non-useful columns from the dataset

In [37]:
df['release_year'] = df['release_year'].astype(int)

In [38]:
drop_cols = [
    'serial_no',
    'cover_image_url',
    'official_website',
    'url_slug',
    'description_clean'
]

df=df.drop(columns=drop_cols)

In [39]:
df.head()

,game_id,title,release_date,release_year,all_genres,theme,art_style,view_dimension,game_mode,is_multiplayer,...,status_toplay,status_yet,all_tags,available_stores,popularity_score,engagement_score,decade,is_multi_platform,rating_tier,metacritic_tier
0,3498,Grand Theft Auto V,2013-09-17,2013,Action,Crime,Realistic,3D,Single & Multiplayer,1,...,630.0,554.0,Singleplayer|Steam Achievements|Multiplayer|Fu...,Steam|PlayStation Store|Epic Games|Xbox 360 St...,96.28,21.75,2010s,1.0,excellent,universal_acclaim
1,3328,The Witcher 3: Wild Hunt,2015-05-18,2015,Action|RPG,Fantasy,Realistic,3D,Singleplayer,0,...,843.0,1181.0,Singleplayer|Full controller support|Atmospher...,GOG|PlayStation Store|Steam|Xbox Store|Nintend...,95.81,17.19,2010s,1.0,masterpiece,universal_acclaim
2,4200,Portal 2,2011-04-18,2011,Shooter|Puzzle,Sci-Fi,Realistic,3D,Single & Multiplayer,1,...,398.0,662.0,Singleplayer|Steam Achievements|Multiplayer|Fu...,Xbox Store|Steam|PlayStation Store|Xbox 360 Store,91.26,15.24,2010s,1.0,masterpiece,universal_acclaim
3,4291,Counter-Strike: Global Offensive,2012-08-21,2012,Shooter,Horror,Realistic,3D,Multiplayer,1,...,79.0,267.0,Steam Achievements|Multiplayer|Full controller...,PlayStation Store|Steam|Xbox 360 Store,73.56,8.79,2010s,1.0,good,generally_favorable
4,5286,Tomb Raider (2013),2013-03-05,2013,Action,Adventure,Realistic,3D,Single & Multiplayer,1,...,286.0,693.0,Singleplayer|Multiplayer|Full controller suppo...,Xbox 360 Store|Steam|PlayStation Store|Google ...,76.54,13.77,2010s,1.0,excellent,generally_favorable

#Saving Dataframe

In [40]:
df.to_csv("games_eda_ready.csv", index=False)

#Connecting Dataframe with SQL server

In [41]:
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql+psycopg2://postgres:postgres123@localhost:5432/gaming_data_analysis"
)

with engine.connect() as conn:
    print("Connected successfully!")

Connected successfully!

#Uploading Dataset to SQL database

In [42]:
df.to_sql(
    name='game_data',
    con=engine,
    if_exists='replace',  
    index=False
)

print("Data uploaded successfully!")

Data uploaded successfully!

In [43]:
#Verifing Connection

In [44]:
pd.read_sql("SELECT * FROM game_data LIMIT 5",engine)

,game_id,title,release_date,release_year,all_genres,theme,art_style,view_dimension,game_mode,is_multiplayer,...,status_toplay,status_yet,all_tags,available_stores,popularity_score,engagement_score,decade,is_multi_platform,rating_tier,metacritic_tier
0,3498,Grand Theft Auto V,2013-09-17,2013,Action,Crime,Realistic,3D,Single & Multiplayer,1,...,630.0,554.0,Singleplayer|Steam Achievements|Multiplayer|Fu...,Steam|PlayStation Store|Epic Games|Xbox 360 St...,96.28,21.75,2010s,1.0,excellent,universal_acclaim
1,3328,The Witcher 3: Wild Hunt,2015-05-18,2015,Action|RPG,Fantasy,Realistic,3D,Singleplayer,0,...,843.0,1181.0,Singleplayer|Full controller support|Atmospher...,GOG|PlayStation Store|Steam|Xbox Store|Nintend...,95.81,17.19,2010s,1.0,masterpiece,universal_acclaim
2,4200,Portal 2,2011-04-18,2011,Shooter|Puzzle,Sci-Fi,Realistic,3D,Single & Multiplayer,1,...,398.0,662.0,Singleplayer|Steam Achievements|Multiplayer|Fu...,Xbox Store|Steam|PlayStation Store|Xbox 360 Store,91.26,15.24,2010s,1.0,masterpiece,universal_acclaim
3,4291,Counter-Strike: Global Offensive,2012-08-21,2012,Shooter,Horror,Realistic,3D,Multiplayer,1,...,79.0,267.0,Steam Achievements|Multiplayer|Full controller...,PlayStation Store|Steam|Xbox 360 Store,73.56,8.79,2010s,1.0,good,generally_favorable
4,5286,Tomb Raider (2013),2013-03-05,2013,Action,Adventure,Realistic,3D,Single & Multiplayer,1,...,286.0,693.0,Singleplayer|Multiplayer|Full controller suppo...,Xbox 360 Store|Steam|PlayStation Store|Google ...,76.54,13.77,2010s,1.0,excellent,generally_favorable

# Creating dimension tables from multi-valued attributes for analytical modeling

#1. Genre Table

In [45]:
genre_table = (
                df[['game_id', 'all_genres']].copy()
)

genre_table['all_genres'] = (
                            genre_table['all_genres'].str.split('|')
)

genre_table = genre_table.explode('all_genres')

genre_table.rename(
                    columns={'all_genres': 'genre'},inplace=True
)

genre_table['genre'] = genre_table['genre'].str.strip()

genre_table.head()

  game_id    genre
0    3498   Action
1    3328   Action
1    3328      RPG
2    4200  Shooter
2    4200   Puzzle

In [46]:
genre_table.shape

(38208, 2)

In [47]:
genre_table['genre'].nunique()

19

In [48]:
genre_table.duplicated().sum()

np.int64(0)

#2. Platform Table

In [49]:
platform_table = (
                    df[['game_id', 'all_platforms']].copy()
)

platform_table['all_platforms'] = (
                                    platform_table['all_platforms'].str.split('|')
)

platform_table = platform_table.explode('all_platforms')

platform_table.rename(
                        columns={'all_platforms':'platform'},inplace=True
)

platform_table['platform'] = (
                                platform_table['platform'].str.strip()
)

platform_table.drop_duplicates(inplace=True)

#3. Tag Table

In [50]:
tag_table = (
                df[['game_id', 'all_tags']].copy()
)

tag_table['all_tags'] = (
                            tag_table['all_tags'].str.split('|')
)

tag_table = tag_table.explode('all_tags')

tag_table.rename(
                    columns={'all_tags':'tag'},inplace=True
)

tag_table['tag'] = tag_table['tag'].str.strip()

tag_table.drop_duplicates(inplace=True)

#4. Store Table

In [51]:
store_table = (
                df[['game_id', 'available_stores']].copy()
)

store_table['available_stores'] = (
                                    store_table['available_stores'].str.split('|')
)

store_table = store_table.explode('available_stores')

store_table.rename(
                    columns={'available_stores':'store'},inplace=True
)

store_table['store'] = store_table['store'].str.strip()

store_table.drop_duplicates(inplace=True)

In [52]:
print("Games:", df.shape)

print("Genres:", genre_table.shape)
print("Platforms:", platform_table.shape)
print("Tags:", tag_table.shape)
print("Stores:", store_table.shape)

Games: (14999, 38)
Genres: (38208, 2)
Platforms: (39068, 2)
Tags: (177985, 2)
Stores: (28781, 2)

In [53]:
print(genre_table['genre'].nunique())

print(platform_table['platform'].nunique())

print(tag_table['tag'].nunique())

print(store_table['store'].nunique())

19
50
2402
12

In [54]:
genre_table.to_csv('genre_table.csv', index=False)

platform_table.to_csv('platform_table.csv', index=False)

tag_table.to_csv('tag_table.csv', index=False)

store_table.to_csv('store_table.csv', index=False)

#Uploading Dimensions table to SQL server

In [56]:
import pandas as pd

genre_table = pd.read_csv("genre_table.csv")
platform_table = pd.read_csv("platform_table.csv")
store_table = pd.read_csv("store_table.csv")
tag_table = pd.read_csv("tag_table.csv")

In [44]:
genre_table.to_sql(
    "genre_table",
    engine,
    if_exists="replace",
    index=False
)

platform_table.to_sql(
    "platform_table",
    engine,
    if_exists="replace",
    index=False
)

store_table.to_sql(
    "store_table",
    engine,
    if_exists="replace",
    index=False
)

tag_table.to_sql(
    "tag_table",
    engine,
    if_exists="replace",
    index=False
)

985